from enum import StrEnum


class CustomerStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class AccountType(StrEnum):
    PREPAID = "PREPAID"
    POSTPAID = "POSTPAID"


class AccountStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class SimStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DEACTIVATED = "DEACTIVATED"


class PlanType(StrEnum):
    LOCAL = "LOCAL"
    ROAMING = "ROAMING"
    ADD_ON = "ADD_ON"


class SubscriptionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ENDED = "ENDED"
    CANCELLED = "CANCELLED"


class LedgerEntryType(StrEnum):
    RECHARGE = "RECHARGE"
    PLAN_BUY = "PLAN_BUY"


class UsageType(StrEnum):
    STREAMING = "STREAMING"
    BROWSING = "BROWSING"
    VOICE = "VOICE"
    OTHER = "OTHER"


class InteractionType(StrEnum):
    COMPLAINT = "COMPLAINT"
    NETWORK_ISSUE = "NETWORK_ISSUE"
    BILLING_ISSUE = "BILLING_ISSUE"
    PACKAGE_ISSUE = "PACKAGE_ISSUE"


class InteractionStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"


class LoyaltyEntryType(StrEnum):
    EARN = "EARN"
    REDEEM = "REDEEM"


class CampaignInteractionType(StrEnum):
    RECEIVED = "RECEIVED"
    OPENED = "OPENED"
    CLICKED = "CLICKED"
    CONVERTED = "CONVERTED"
    IGNORED = "IGNORED"


class InventoryEventType(StrEnum):
    STOCK_IN = "STOCK_IN"
    SALE = "SALE"
    ADJUSTMENT = "ADJUSTMENT"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"


class EventType(StrEnum):
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    DEVICE_LINKED = "DEVICE_LINKED"
    RECHARGE_RECORDED = "RECHARGE_RECORDED"
    PLAN_PURCHASED = "PLAN_PURCHASED"
    USAGE_RECORDED = "USAGE_RECORDED"
    TRAVEL_STARTED = "TRAVEL_STARTED"
    TRAVEL_ENDED = "TRAVEL_ENDED"
    TRAVEL_CORRECTED = "TRAVEL_CORRECTED"
    WARNING_RAISED = "WARNING_RAISED"
    SERVICE_INTERACTION_RECORDED = "SERVICE_INTERACTION_RECORDED"


class WarningType(StrEnum):
    IMPOSSIBLE_TRAVEL = "IMPOSSIBLE_TRAVEL"
    OVERLAPPING_TRAVEL = "OVERLAPPING_TRAVEL"
    FREQUENT_SMALL_RECHARGE_PATTERN = "FREQUENT_SMALL_RECHARGE_PATTERN"
    DUPLICATE_DEVICE = "DUPLICATE_DEVICE"
    UNUSUAL_RECHARGE = "UNUSUAL_RECHARGE"
    ABNORMAL_TRANSACTION_VELOCITY = "ABNORMAL_TRANSACTION_VELOCITY"
    STOCKOUT_RISK = "STOCKOUT_RISK"


class WarningSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class DecisionMode(StrEnum):
    SINGLE_RECOMMENDATION = "SINGLE_RECOMMENDATION"
    RANKED_OPTIONS = "RANKED_OPTIONS"
    SCENARIO_BASED = "SCENARIO_BASED"
    ASK_FOR_INFORMATION = "ASK_FOR_INFORMATION"
    NO_RECOMMENDATION = "NO_RECOMMENDATION"
