repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
        files: ^src/

  - repo: local
    hooks:
      - id: check-env-variables
        name: Check environment variables
        language: python
        entry: python scripts/check_env_variables.py
        pass_filenames: false
        always_run: true
