[project]
name = "telco-digital"
version = "0.1.0"
description = "Telco digital Python project"
authors = [
    {name = "Pamudu",email = "pamudu123456789@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.34.2,<3.0.0)"
]

[tool.poetry]
packages = [{include = "telco_digital", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
