from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Protocol, Sequence
from uuid import UUID

from telco_digital.domain.entities import (
    Account,
    ActivityEvent,
    BalanceLedgerEntry,
    Customer,
    CustomerDevice,
    Device,
    OutboxEvent,
    Plan,
    Recharge,
    ServiceInteraction,
    Subscription,
    Travel,
    UsageEvent,
    Warning,
)
from telco_digital.domain.enums import PlanType, UsageType


class CustomerRepository(Protocol):
    async def add(self, customer: Customer) -> None: ...
    async def get_by_id(self, customer_id: UUID) -> Customer | None: ...
    async def get_by_ref(self, customer_ref: str) -> Customer | None: ...
    async def list_all(self) -> Sequence[Customer]: ...


class AccountRepository(Protocol):
    async def add(self, account: Account) -> None: ...
    async def get_by_id(self, account_id: UUID) -> Account | None: ...
    async def list_by_customer(self, customer_id: UUID) -> Sequence[Account]: ...


class DeviceRepository(Protocol):
    async def add(self, device: Device) -> None: ...
    async def get_by_id(self, device_id: UUID) -> Device | None: ...
    async def get_by_ref(self, device_ref: str) -> Device | None: ...


class CustomerDeviceRepository(Protocol):
    async def add(self, link: CustomerDevice) -> None: ...
    async def list_by_customer(self, customer_id: UUID) -> Sequence[CustomerDevice]: ...
    async def list_by_device(self, device_id: UUID) -> Sequence[CustomerDevice]: ...
    async def active_at(self, customer_id: UUID, as_of: datetime) -> CustomerDevice | None: ...


class PlanRepository(Protocol):
    async def add(self, plan: Plan) -> None: ...
    async def get_by_id(self, plan_id: UUID) -> Plan | None: ...
    async def get_by_code(self, plan_code: str) -> Plan | None: ...
    async def list_active(
        self, *, plan_type: PlanType | None = None, country_code: str | None = None
    ) -> Sequence[Plan]: ...


class SubscriptionRepository(Protocol):
    async def add(self, subscription: Subscription) -> None: ...
    async def list_by_customer(self, customer_id: UUID) -> Sequence[Subscription]: ...
    async def active_at(
        self,
        customer_id: UUID,
        as_of: datetime,
        *,
        plan_type: PlanType | None = None,
    ) -> Subscription | None: ...
    async def update(self, subscription: Subscription) -> None: ...


class LedgerRepository(Protocol):
    async def add(self, entry: BalanceLedgerEntry) -> None: ...
    async def list_by_customer(self, customer_id: UUID) -> Sequence[BalanceLedgerEntry]: ...
    async def balance_at(self, account_id: UUID, as_of: datetime) -> Decimal: ...


class RechargeRepository(Protocol):
    async def add(self, recharge: Recharge) -> None: ...
    async def list_by_customer(self, customer_id: UUID) -> Sequence[Recharge]: ...
    async def list_as_of(self, customer_id: UUID, as_of: datetime) -> Sequence[Recharge]: ...


class UsageRepository(Protocol):
    async def add(self, usage: UsageEvent) -> None: ...
    async def list_by_customer(self, customer_id: UUID) -> Sequence[UsageEvent]: ...
    async def list_as_of(self, customer_id: UUID, as_of: datetime) -> Sequence[UsageEvent]: ...
    async def total_mb(
        self,
        customer_id: UUID,
        *,
        start: datetime,
        end: datetime,
        usage_type: UsageType | None = None,
    ) -> Decimal: ...


class TravelRepository(Protocol):
    async def add(self, travel: Travel) -> None: ...
    async def list_by_customer(self, customer_id: UUID) -> Sequence[Travel]: ...
    async def list_as_of(self, customer_id: UUID, as_of: datetime) -> Sequence[Travel]: ...
    async def update(self, travel: Travel) -> None: ...


class ServiceInteractionRepository(Protocol):
    async def add(self, interaction: ServiceInteraction) -> None: ...
    async def list_by_customer(self, customer_id: UUID) -> Sequence[ServiceInteraction]: ...
    async def open_count(self, customer_id: UUID, as_of: datetime) -> int: ...


class EventRepository(Protocol):
    async def add(self, event: ActivityEvent) -> None: ...
    async def list_timeline(
        self, customer_id: UUID, *, as_of: datetime | None = None
    ) -> Sequence[ActivityEvent]: ...


class OutboxRepository(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...
    async def list_pending(self, limit: int = 100) -> Sequence[OutboxEvent]: ...


class WarningRepository(Protocol):
    async def add(self, warning: Warning) -> None: ...
    async def list_by_customer(
        self, customer_id: UUID, *, as_of: datetime | None = None
    ) -> Sequence[Warning]: ...


class UnitOfWork(Protocol):
    customers: CustomerRepository
    accounts: AccountRepository
    devices: DeviceRepository
    customer_devices: CustomerDeviceRepository
    plans: PlanRepository
    subscriptions: SubscriptionRepository
    ledgers: LedgerRepository
    recharges: RechargeRepository
    usage_events: UsageRepository
    travels: TravelRepository
    service_interactions: ServiceInteractionRepository
    events: EventRepository
    outbox: OutboxRepository
    warnings: WarningRepository

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def __aenter__(self) -> UnitOfWork: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
